fruits = ["Apple",
                "Banana",
                "Cherry",
                "Durian",
                "Elderberry",
                "Fig",
                "Grape",
                "Honeydew",
                "Jackfruit",
                "Kiwi",
                "Lemon",
                "Mango",
                "Nectarine",
                "Orange",
                "Papaya",
                "Quince",
                "Raspberry",
                "Strawberry",
                "Tangerine",
                "Ugli fruit",
                "Watermelon"
]